version: '3.9'  # Version sesuai dengan spesifikasi Docker Compose
name: 'nginx-mysql-stack'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"  # Akses NGINX melalui port 8080
    volumes:
      - nginx_data:/usr/share/nginx/html  # Volume untuk laman HTML
      - ./config/nginx.conf:/etc/nginx/nginx.conf  # File konfigurasi NGINX
    networks:
      - app_network
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"  # Akses MySQL melalui port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Volume untuk menyimpan data database
    networks:
      - app_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_service
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"  # Akses PGAdmin di port 5050
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  nginx_data:  # Volume untuk NGINX HTML files
  mysql_data:  # Volume untuk MySQL database

configs:
  nginx_conf:
    file: ./config/nginx.conf  # Konfigurasi custom untuk NGINX
