version: '3.9'

name: DianRafaelProject

services:
  # 1. HTTP Server: NGINX
  nginx:
    image: nginx:latest
    container_name: nginx_http
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  # 2. HTTP Server: PGAdmin (untuk manajemen PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_http
    environment:
      PGADMIN_DEFAULT_EMAIL: 24031554166@mhs.unesa.ac.id
      PGADMIN_DEFAULT_PASSWORD: passadminakso
    ports:
      - "8080:80" 
    networks:
      - app_network

  # 3. HTTP Server: Apache HTTPD
  apache:
    image: httpd:latest
    container_name: apache_http
    ports:
      - "8081:80"
    networks:
      - app_network

  # 4. HTTP Server: Wordpress
  wordpress:
    image: wordpress:latest
    container_name: wordpress_webserver
    environment:
      WORDPRESS_DB_HOST: mysql_db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userkeren456
      WORDPRESS_DB_NAME: wordpress_db
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - app_network

  # 5. Database Server: MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootakso123
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userkeren456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  # 6. Database Server: PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres_dB
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgakso789
      POSTGRES_DATABASE: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  # 7. Database Server: MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  # 8. Database Server: Neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    environment:
      NEO4J_AUTH: neo4j/neoakso123
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  mongo_data:
    driver: local